spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    password: 1234
    user: t_user
    url: jdbc:postgresql://localhost:5432/db_translator
  application:
    name: translator
    count-thread: 10
  datasource:
    url: jdbc:postgresql://localhost:5432/db_translator
    username: t_user
    password: 1234
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 60000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: MyHikariCPPool
yandex:
  api:
    key: t1.9euelZqNx5OWk5qWi5maicrNzsmNje3rnpWampeMl8mQyJGNzZaKi8majsnl8_csXj9K-e8BG2Bk_d3z92wMPUr57wEbYGT9zef1656VmovJyZiaiprKlZaZjJiPj8uP7_zF656VmovJyZiaiprKlZaZjJiPj8uP.oIk6dNQ_r_FRzXfK326KsfPrFKFSNf__H2rBHdtzRxOa1v_x2Vlkqcf1csoTK9T7JuG8rEOaHz7oKqGEtDXUCg
    folder-id: b1gja17a30lnndt64g1r
    translate-url: https://translate.api.cloud.yandex.net/translate/v2/translate